token: null  # Insert bot-API token here
# MTProto API tokens. Get them from https://my.telegram.org/
api-id: null
api-hash: null

# Localisation settings
language: ru
fallback-language: en

# Whether to try update module dependencies at every load
update_deps_at_load: true

mods_repos: "PBModularModules"

### Database section ###
enable-db: true

# Database backend selection. Fill only type and driver! <type>[+<driver>]://
# Useful links for setting this properly:
# https://docs.sqlalchemy.org/en/20/tutorial/engine.html#establishing-connectivity-the-engine
# https://docs.sqlalchemy.org/en/20/dialects/ (Supported backends)
# https://docs.sqlalchemy.org/en/20/core/engines.html#backend-specific-urls
db-url: "sqlite+aiosqlite://"

# SQLite only! Name for database file inside modules directory
db-file-name: "db.sqlite3"

# Bot owner Telegram ID or username
owner: "sanyapilot"
